package com.example.quizuz

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.example.quizuz.adapter.TopicCallback
import com.example.quizuz.adapter.TopicsAdapter
import com.example.quizuz.model.QuestionsModel
import com.example.quizuz.model.TopicModel
import kotlinx.android.synthetic.main.activity_topics.*

class TopicsActivity : AppCompatActivity() {

    val topicList = listOf(
        TopicModel("Astronomiya", listOf(
            QuestionsModel("Quyosh sistemasida nechta sayyora mavjud?",
                null,
                "6",
                "7",
                "8",
                "9",
                "C"),
            QuestionsModel("Eng katta sayyora qaysi?",
                null,
                "Yupiter",
                "Saturn",
                "Merkuriy",
                "Mars",
                "A"),
            QuestionsModel("Eng katta galaktika qaysi?",
                null,
                "Andromeda",
                "Somon Yo'li",
                "Qora ko'z",
                "Komet",
                "A"),
            QuestionsModel("Quyosh sistemasidagi eng kichik sayyora qaysi?",
                null,
                "Mars",
                "Neptun",
                "Yer",
                "Merkuriy",
                "D"),
            QuestionsModel("Quyosh sistemamizdagi eng kichik ikkinchi sayyora qaysi?",
                null,
                "Yer",
                "Venera",
                "Mars",
                "Neptun",
                "C"),
            QuestionsModel("Titan deb nomlangan oy qaysi sayyora atrofida aylanadi?",
                null,
                "Mars",
                "Saturn",
                "Yupiter",
                "Merkuriy",
                "B"),
            QuestionsModel("Tungi osmondagi eng yorqin sayyora qaysi?",
                null,
                "Venera",
                "Mars",
                "Oy",
                "Saturn",
                "A"),
            QuestionsModel("Uran atrofidan qaysi kosmik kema uchib o'tgan?",
                null,
                "Saturn V",
                "Voyajer 1",
                "Voyajer 2",
                "Spirit",
                "C"),
            QuestionsModel("Yunon xudolari yoki ma'budalari nomi bilan atalmagan yagona sayyora qaysi?",
                null,
                "Mars",
                "Uran",
                "Yer",
                "Yupiter",
                "C"),
            QuestionsModel("Yerni meteoroidlardan va quyosh nurlanishidan nima himoya qiladi?",
                null,
                "Yer atmosferasi",
                "Sun'iy yo'ldoshlar",
                "Harbiy qurollar",
                "Oy",
                "A"),
            QuestionsModel("Fobos va Deymos qaysi sayyora Oylari?",
                null,
                "Neptun",
                "Saturn",
                "Mars",
                "Yupiter",
                "C"),
            QuestionsModel("Qaysi sayyora hajmi jihatidan Yerga eng yaqin?",
                null,
                "Mars",
                "Merkuriy",
                "Venera",
                "Neptun",
                "C"),
            QuestionsModel("Qaysi sayyorada eng ko'p oy bor?",
                null,
                "Yupiter",
                "Saturn",
                "Mars",
                "Neptun",
                "B"),
            QuestionsModel("Qaysi sayyoralarda oy yo'q?",
                null,
                "Merkuriy va Venerada",
                "Oy va Venerada",
                "Uran va Neptunda",
                "Venera va Uranda",
                "A"),
            QuestionsModel("Qaysi sayyorada ovozdan tez shamollar bor?",
                null,
                "Uran",
                "Saturn",
                "Yupiter",
                "Neptun",
                "C"),
            )),

        TopicModel("Tarix", listOf(
            QuestionsModel("1944 yilda Islandiya qaysi davlatdan mustaqillikka erishdi?",
                null,
                "Angliya",
                "Daniya",
                "Fransiya",
                "Norvegiya",
                "B"),
            QuestionsModel("AQShning birinchi poytaxti qaysi shahar bo'lgan?",
                null,
                "Boston",
                "Vashington",
                "Los-Anjeles",
                "Nyu-York",
                "D"),
            QuestionsModel("Amerika bayrog'i nechta yulduzga ega?",
                null,
                "40ta",
                "30ta",
                "50ta",
                "47ta",
                "C"),
            QuestionsModel("Osiyoning qaysi davlatida insoniyat tarixidagi eng halokatli o'nta urushning ettitasi 1chi jahon urushidan ham dahshatli bo'lgan?",
                null,
                "Eronda",
                "Xitoyda",
                "Buxoro xonligida",
                "Usmonli turklarda",
                "B"),
            QuestionsModel("Dunyo tarixidagi eng katta imperiya?",
                null,
                "Mo'g'ul imperiyasi",
                "Rim imperiyasi",
                "Temuriylar imperiyasi",
                "Usmonli Turklar imperiyasi",
                "A"),
            QuestionsModel("Napoleon Bonapart qaysi yilda tu'g'ilgan?",
                null,
                "1769-yilda",
                "1554-yilda",
                "1651-yilda",
                "1889-yilda",
                "A"),
            QuestionsModel("Qadimgi Rim davrida bir haftada necha kun bo'lgan?",
                null,
                "6",
                "10",
                "8",
                "7",
                "C"),
            QuestionsModel("1944 yilda Islandiya qaysi davlatdan mustaqillikka erishdi?",
                null,
                "Angliya",
                "Daniya",
                "Fransiya",
                "Norvegiya",
                "B"),
            QuestionsModel("Oyda yurgan birinchi odam kim edi?",
                null,
                "Yuriy Gagarin",
                "Neil Armstrong",
                "Joe Edwards",
                "Hali hech kim oyda bo'lmagan",
                "B"),
            QuestionsModel("Qaysi yunon tarixchisi \"tarixning otasi\" sifatida tanilgan?",
                null,
                "Gerodot",
                "Isaak Nyuton",
                "Aristotel",
                "Ptolomey",
                "A"),
            QuestionsModel("Birinchi insoniyat sivilizatsiyasi qayerda paydo bo'lgan?",
                null,
                "Misr",
                "Ossuriya",
                "Bobil",
                "Mesopotamiya",
                "D"),
            QuestionsModel("Mona Liza surati necha marta o'g'irlangan?",
                null,
                "2 marta",
                "1 marta",
                "5 marta",
                "9 marta",
                "B"),
            QuestionsModel("Adolf Gitler qaerda tug'ilgan?",
                null,
                "Avstriyada",
                "Germaniyada",
                "Daniyada",
                "Shvetsariyada",
                "A"),
            QuestionsModel("Yuz yillik urush qaysi ikki davlat o'rtasida olib borilgan?",
                null,
                "Angliya va Fransiya",
                "Daniya va Fransiya",
                "Rossiya va Fransiya",
                "Germaniya va Angliya",
                "A"),
            QuestionsModel("Insoniyat qaysi yilda birinchi sun'iy yo'ldoshni orbitaga chiqardi?",
                null,
                "1964",
                "1980",
                "1957",
                "1943",
                "C"),
        ))
    )
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_topics)

        topic_back_button.setOnClickListener {
            finish()
        }
        topic_recyclerview.layoutManager = LinearLayoutManager(this, RecyclerView.VERTICAL, false)
        topic_recyclerview.adapter = TopicsAdapter(topicList, object: TopicCallback{
            override fun onClick(item: TopicModel) {
                val intent = Intent(this@TopicsActivity, QuizActivity::class.java)
                intent.putExtra("Extra", item)
                startActivity(intent)
            }
        })
    }
}